env: "gymma"

env_args:
  key: null
  time_limit: 2 #100
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 10 #100
test_interval: 5 #50000
log_interval: 50
runner_log_interval: 10 #10000
learner_log_interval: 10 #1000
t_max: 2050 #2050000
