env: "gymma"

env_args:
  key: null
  time_limit: 100
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 5
test_interval: 50000
log_interval: 50000
runner_log_interval: 50000
learner_log_interval: 50000
buffer_size: 5
batch_size: 5
lr: 0.001
t_max: 2050000
epochs: 2
target_update_interval_or_tau: 500
# test_greedy: True
# test_nepisode: 5
# test_interval: 50000
# log_interval: 5
# runner_log_interval: 100
# learner_log_interval: 100
# buffer_size: 5
# batch_size: 5
# lr: 0.001
# t_max: 50000
# epochs: 2
# target_update_interval_or_tau: 500

